force-app/main/default/objects/Cost__c/Cost__c.object-meta.xml
<CustomObject>
    <label>Cost</label>
    <nameField>
        <label>Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cost__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost__c/fields/Paperwork__c.field-meta.xml
<CustomField>
    <fullName>Paperwork__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Paperwork</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Paperwork__c.Type__c</field>
            <operation>equals</operation>
            <value>Cost confirmation</value>
        </filterItems>
        <filterItems>
            <field>Paperwork__c.Opportunity__r.StageName</field>
            <operation>notContain</operation>
            <value>Proposal/Price Quote, Negotiation/Review, Closed Won, Closed Lost</value>
        </filterItems>
        <filterItems>
            <field>$Source.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>Paperwork__c.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Paperwork__c</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paperwork__c/Paperwork__c.object-meta.xml
<CustomObject>
    <label>Paperwork</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Paperwork Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paperworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Paperwork__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Paperworks</relationshipLabel>
    <relationshipName>Paperworks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paperwork__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Paperworks</relationshipLabel>
    <relationshipName>Paperworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paperwork__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Cost confirmation</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>Annex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddCostFormController.cls
public with sharing class AddCostFormController {
    
    @AuraEnabled(Cacheable=true)
    public static List<Paperwork__c> getAvailablePaperworks(String opportunityId){
        return [SELECT Id, Name, Account__r.Name FROM Paperwork__c WHERE Opportunity__r.Id = :opportunityId AND Account__c != null AND Type__c = 'Cost confirmation'];
    }
    @AuraEnabled(Cacheable=false)
    public static Boolean saveCost(String formValuesInput){
        
        if(formValuesInput==null) return false;
        
        Cost__c cost = new Cost__c();
        
        try{
            FormValuesObject formValues = (FormValuesObject)JSON.deserialize(formValuesInput, FormValuesObject.class);
            if(String.isNotBlank(formValues.name)) cost.Name = formValues.name;
            cost.Account__c = formValues.account;
            cost.Opportunity__c = formValues.opportunity;
            cost.Paperwork__c = formValues.paperwork;
            cost.Amount__c = formValues.amount;
            Insert cost;
            
            if(formValues.amount<=10000) return true;
            
            Approval.ProcessSubmitRequest approvalRequest = new Approval.ProcessSubmitRequest();
            approvalRequest.setComments('Cost Submitted for approval');
            approvalRequest.setObjectId(cost.Id);
            Approval.ProcessResult approvalResult = Approval.process(approvalRequest);
            return approvalResult.isSuccess();
        
        }catch(Exception e){
            return false;
        }
        
    }
    
    public class FormValuesObject {
        public String name;
        public Id account;
        public Id opportunity;
        public Id paperwork;
        public Decimal amount;
    }
}